### ISSUE TITLE
Cannot read properties of undefined (reading 'message')

### ISSUE THREAD

**Issue by NullVoxPopuli** [psbanka/eslint-plugin-hbs#51]
```
TypeError: Cannot read properties of undefined (reading 'message')
Occurred while linting /✂️/addon/components/my-component.ts:42
    at TaggedTemplateExpression (/✂️/node_modules/eslint-plugin-hbs/lib/rules/check-hbs-template-literals.js:80:44)
    at /✂️/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/✂️/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/✂️/node_modules/eslint/lib/linter/node-event-generator.js:293:26)
    at NodeEventGenerator.applySelectors (/✂️node_modules/eslint/lib/linter/node-event-generator.js:322:22)
    at NodeEventGenerator.enterNode (/✂️/node_modules/eslint/lib/linter/node-event-generator.js:336:14)
    at CodePathAnalyzer.enterNode (/✂️/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:711:23)
    at /✂️/node_modules/eslint/lib/linter/linter.js:960:32
    at Array.forEach (<anonymous>)
```
    
code:
    
```ts
setComponentTemplate(hbs`
  my template
  `,
  MyComponent
);    
```

**Comment by NullVoxPopuli** [comment]
oh nevermind, this same error occurs in javascript as well.
Seems the plugin just doesn't work?

**Comment by Turbo87** [comment]
see #42
